- id: scalafmt
  name: scalafmt
  language: python
  entry: run-sbt-command
  args: [--command, set ThisBuild / scalafmtFilter := "diff-dirty"; scalafmt]
  pass_filenames: false
  description: Format scala code
