[build-system]
requires = [
    "setuptools >= 65.3.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "pre-commit-sbt"
version = "0.0.1beta"
description = "A set of pre-commit hooks which integrate well with SBT (for scala)."
readme = "README.md"

[project.optional-dependencies]
dev = [
    "mypy==0.971",
    "pre-commit==2.20.0",
    "pylint==2.15.3",
    "pytest==7.1.3",
    "tox==3.26.0",
]

[tool.black]
line-length = 120

[tool.mypy]
strict = true

[tool.pylint]
disable = ["C0114", "C0116"]
good-names = ["f"]
max-line-length = 120
